routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'middleware' => ['role:admin']], function() {
Route::resource('dashboard','DashboardController');
Route::resource('roles','RoleController');
Route::resource('users','UserController');
Route::resource('dictionary','DictionaryController');

});

Route::group(['middleware' => ['role:user']], function() {
Route::resource('dashboard','DashboardController');
});

 Route::view('messages_table', 'partials.messages', [
      'data' => App\Message::orderBy('created_at', 'desc')->take(20)->get()
    ]);

Route::resource('messages','MessageController');
Route::post('saveMessage', 'MessageController@saveMessage');

resources/views/partials/dictionary.blade.php
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <div class="container col-md-8">
        <div class="row">
            <div class="col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading" style="font-style: bold;"><h4>Diccionario</h4>
                      <a href="{{ route('dictionary.create') }}" class="btn btn-warning col-md-4" style="text-right: center; display: inline-block;">Nueva palabra</a>
                      </div>
                    <div class="panel-body">
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif
                        <table id="table" class="table table-bordered table-hover dataTable table-striped" role="grid">
                            <thead>
                            <tr>
                                <th>Id</th>
                                <th class="success">Nombre</th>
                                <th>Creación</th>
                                <th>Funcionalidades</th>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach ($dictionary as $dic)

                                <tr class="success">
                                    <td class="warning">{{$dic->id}}</td>
                                    <td class="success">{{$dic->word}}</td>
                                    <td class="warning">{{$dic->updated_at}}</td>
                                    <td>
                                        
                                        <a class="btn btn-primary" href="{{ route('dictionary.edit',$dic->id) }}">Editar</a>
                                        <form action="{{ url('admin/dictionary/'.$dic->id) }}" method="POST" style="display: inline-block">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}

                                            <button type="submit" id="delete-task-{{ $dic->id }}" class="btn btn-danger">
                                                <i class="fa fa-btn fa-trash"></i>Eliminar
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>

resources/views/partials/messages.blade.php
<h3 class="box-title" style="text-align: center;">Chat grupal</h3>

    <table id="table" class="table table-bordered table-hover dataTable table-striped col-md-8 offset-md-2" role="grid" >
         <thead>
            <tr class="danger">
                <th >ID</th>
                <th >Usuario</th>
                <th >Mensaje</th>
                <th colspan="3" nowrap>Enviado</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $message)
                <tr>
                    <td>{{$message->id}}</td>
                    <td>{{$message->user->name}}</td>
                    <td>{{$message->content}}</td>
                    <td>{{$message->created_at }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>           